{{- range .Values.dataSources.databricks }}
{{- if and .name .token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | default (printf "%s-credentials" .name) | quote }}
  namespace: {{ include "kagent.namespace" $ }}
  labels:
    {{- include "kagent.labels" $ | nindent 4 }}
type: Opaque
data:
  token: {{ .token | b64enc }}
{{- end }}
{{- end }}
