{{- if .Values.dataSources.databricksShared }}
{{- with .Values.dataSources.databricksShared }}
{{- if and .secretName .token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | quote }}
  namespace: {{ include "kagent.namespace" $ }}
  labels:
    {{- include "kagent.labels" $ | nindent 4 }}
type: Opaque
data:
  token: {{ .token | b64enc }}
{{- end }}
{{- end }}
{{- end }}
