{{- if and .Values.databricks.enabled .Values.databricks.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databricks.secretName | quote }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.databricks.secretKey }}: {{ .Values.databricks.token | b64enc }}
{{- end }}
